package analyzer

import (
	"fmt"
	"strings"

	"github.com/firewall-analyzer/internal/terraform"
)

// Reporter generates structured markdown PR comment reports.
type Reporter struct {
	riskEngine *RiskEngine
}

// NewReporter creates a new Reporter.
func NewReporter(riskEngine *RiskEngine) *Reporter {
	return &Reporter{riskEngine: riskEngine}
}

// AnalysisReport represents the complete analysis of a PR.
type AnalysisReport struct {
	FileDiffs  []FileDiff
	TotalScore RiskScore
}

// FileDiff pairs a filename with its computed diff result.
type FileDiff struct {
	Filename string
	Diff     *terraform.DiffResult
	Score    RiskScore
}

// GenerateComment renders a complete markdown PR comment from an AnalysisReport.
func (r *Reporter) GenerateComment(report *AnalysisReport) string {
	if len(report.FileDiffs) == 0 || !r.hasFirewallChanges(report) {
		return ""
	}

	var sb strings.Builder

	sb.WriteString("## 🔎 Terraform AWS Network Firewall Analysis\n\n")
	sb.WriteString("> **Automated security analysis of AWS Network Firewall Terraform changes.**\n\n")

	// Overall risk score banner.
	score := report.TotalScore
	badge := riskBadge(score.Level)
	sb.WriteString(fmt.Sprintf("### 🚨 Overall Risk Score: %.1f/%.0f %s\n\n", score.Score, score.MaxScore, badge))

	// Per-file change summaries.
	sb.WriteString("---\n\n")
	sb.WriteString("### 📌 Changes Detected\n\n")

	for _, fd := range report.FileDiffs {
		if !fd.Diff.HasFirewall || len(fd.Diff.Changes) == 0 {
			continue
		}

		sb.WriteString(fmt.Sprintf("#### 📄 `%s` — Risk: %.1f/10 %s\n\n", fd.Filename, fd.Score.Score, riskBadge(fd.Score.Level)))

		for _, change := range fd.Diff.Changes {
			icon := severityIcon(change.Severity)
			sb.WriteString(fmt.Sprintf("- %s **[%s]** %s", icon, string(change.ChangeType), change.Description))
			if change.Before != "" && change.After != "" {
				sb.WriteString(fmt.Sprintf("\n  - Before: `%s`\n  - After:  `%s`", change.Before, change.After))
			} else if change.After != "" {
				sb.WriteString(fmt.Sprintf("\n  - Value: `%s`", change.After))
			} else if change.Before != "" {
				sb.WriteString(fmt.Sprintf("\n  - Removed: `%s`", change.Before))
			}
			sb.WriteString("\n")
		}
		sb.WriteString("\n")
	}

	// Security impact section.
	sb.WriteString("---\n\n")
	sb.WriteString("### 🔐 Security Impact\n\n")
	sb.WriteString(r.generateImpactSummary(report))
	sb.WriteString("\n")

	// Reviewer checklist.
	sb.WriteString("---\n\n")
	sb.WriteString("### 📋 Reviewer Checklist\n\n")
	sb.WriteString(r.generateChecklist(report))

	// Footer.
	sb.WriteString("\n---\n")
	sb.WriteString("*Generated by [firewall-analyzer](https://github.com/firewall-analyzer) GitHub App*\n")

	return sb.String()
}

// Aggregate produces an AnalysisReport from multiple file diffs.
func (r *Reporter) Aggregate(fileDiffs []FileDiff) *AnalysisReport {
	report := &AnalysisReport{FileDiffs: fileDiffs}

	// Combine all changes for overall scoring.
	combined := &terraform.DiffResult{}
	for _, fd := range fileDiffs {
		combined.Changes = append(combined.Changes, fd.Diff.Changes...)
		if fd.Diff.HasFirewall {
			combined.HasFirewall = true
		}
	}

	report.TotalScore = r.riskEngine.Score(combined)
	return report
}

func (r *Reporter) hasFirewallChanges(report *AnalysisReport) bool {
	for _, fd := range report.FileDiffs {
		if fd.Diff.HasFirewall {
			return true
		}
	}
	return false
}

func (r *Reporter) generateImpactSummary(report *AnalysisReport) string {
	var sb strings.Builder
	seen := make(map[terraform.ChangeType]bool)

	for _, fd := range report.FileDiffs {
		for _, change := range fd.Diff.Changes {
			if seen[change.ChangeType] {
				continue
			}
			seen[change.ChangeType] = true

			switch change.ChangeType {
			case terraform.ChangeTypeAnySourceAdded:
				sb.WriteString("- **⚠️ Unrestricted Source Traffic:** A rule allows traffic from `0.0.0.0/0` or `ANY`. " +
					"This exposes the network segment to all internet traffic. Confirm this is intentional and that downstream " +
					"controls exist (security groups, NACLs).\n")
			case terraform.ChangeTypeCIDRWidened:
				sb.WriteString("- **📡 CIDR Range Widened:** The source or destination CIDR has been broadened. " +
					"A wider CIDR increases the attack surface by allowing more IP ranges to reach protected resources. " +
					"Ensure only the minimum required IP space is permitted.\n")
			case terraform.ChangeTypeActionChanged:
				sb.WriteString("- **🔀 Rule Action Changed:** A firewall rule's action was modified. " +
					"Changing from DROP/REJECT to PASS/ALLOW permits previously blocked traffic. " +
					"Validate that this aligns with the security policy and that the traffic is inspected at another control point.\n")
			case terraform.ChangeTypeSuricataAction:
				sb.WriteString("- **🔄 Suricata Rule Action Changed:** An IDS/IPS rule action was modified. " +
					"Changing from `drop` to `pass` or `alert` disables active blocking and may allow malicious traffic. " +
					"Confirm threat model justification.\n")
			case terraform.ChangeTypeFQDNWildcard:
				sb.WriteString("- **🌐 Wildcard FQDN Added:** A wildcard domain (e.g., `*.example.com`) was added to the rules source list. " +
					"Wildcards match all subdomains including potentially adversary-controlled subdomains via subdomain takeover. " +
					"Prefer explicit domain entries where possible.\n")
			case terraform.ChangeTypeFQDNAdded:
				sb.WriteString("- **🌐 FQDN Target Added:** A new fully-qualified domain was added. " +
					"Ensure this domain is vendor-controlled and does not represent a supply chain risk.\n")
			case terraform.ChangeTypeNewResource:
				sb.WriteString("- **🆕 New Rule Group:** A new `aws_networkfirewall_rule_group` resource was introduced. " +
					"New rule groups must be reviewed in the context of the complete firewall policy to ensure " +
					"priority ordering does not conflict with existing rules.\n")
			}
		}
	}

	if sb.Len() == 0 {
		sb.WriteString("No high-severity security impacts detected. Review individual changes above for context.\n")
	}

	return sb.String()
}

func (r *Reporter) generateChecklist(report *AnalysisReport) string {
	type checkItem struct {
		condition bool
		text      string
	}

	hasCIDRWidening := r.hasChangeType(report, terraform.ChangeTypeCIDRWidened)
	hasAnySource := r.hasChangeType(report, terraform.ChangeTypeAnySourceAdded)
	hasActionChange := r.hasChangeType(report, terraform.ChangeTypeActionChanged)
	hasSuricataChange := r.hasChangeType(report, terraform.ChangeTypeSuricataAction)
	hasFQDN := r.hasChangeType(report, terraform.ChangeTypeFQDNAdded) || r.hasChangeType(report, terraform.ChangeTypeFQDNWildcard)
	hasNewResource := r.hasChangeType(report, terraform.ChangeTypeNewResource)

	checks := []checkItem{
		{true, "Confirm that this change was reviewed and approved by a security engineer"},
		{true, "Verify the change is documented in your change management system (ticket/RFC)"},
		{hasNewResource, "Confirm new rule group is attached to the correct firewall policy with correct priority"},
		{hasCIDRWidening, "Validate the justification for widening the CIDR range and confirm least-privilege is maintained"},
		{hasAnySource, "Confirm that allowing traffic from `0.0.0.0/0` is intentional and additional controls exist"},
		{hasActionChange, "Confirm the rule action change is aligned with the current threat model and security policy"},
		{hasSuricataChange, "Review Suricata rule action changes with the IDS/IPS team and confirm threat coverage"},
		{hasFQDN, "Verify all new FQDN entries belong to trusted, vendor-controlled domains"},
		{hasFQDN, "Check for wildcard FQDN entries and assess subdomain takeover risk"},
		{true, "Run `terraform plan` output was reviewed and matches this PR diff"},
		{true, "Confirm this change has been tested in a non-production environment"},
		{true, "Ensure firewall rule priorities are correctly ordered (earlier rules take precedence)"},
		{report.TotalScore.Score >= 6, "**HIGH RISK:** Escalate to Security Lead for explicit approval before merging"},
		{report.TotalScore.Score >= 8, "**CRITICAL RISK:** This change requires CISO sign-off before merging"},
	}

	var sb strings.Builder
	for _, c := range checks {
		if c.condition {
			sb.WriteString(fmt.Sprintf("- [ ] %s\n", c.text))
		}
	}

	return sb.String()
}

func (r *Reporter) hasChangeType(report *AnalysisReport, ct terraform.ChangeType) bool {
	for _, fd := range report.FileDiffs {
		for _, change := range fd.Diff.Changes {
			if change.ChangeType == ct {
				return true
			}
		}
	}
	return false
}

func riskBadge(level RiskLevel) string {
	switch level {
	case RiskLevelCritical:
		return "🔴 CRITICAL"
	case RiskLevelHigh:
		return "🟠 HIGH"
	case RiskLevelMedium:
		return "🟡 MEDIUM"
	case RiskLevelLow:
		return "🟢 LOW"
	default:
		return "⚪ UNKNOWN"
	}
}

func severityIcon(s terraform.Severity) string {
	switch s {
	case terraform.SeverityCritical:
		return "🔴"
	case terraform.SeverityHigh:
		return "🟠"
	case terraform.SeverityMedium:
		return "🟡"
	case terraform.SeverityLow:
		return "🟢"
	default:
		return "⚪"
	}
}
